// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0406

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0406Client is the client API for Zhaoh0406 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0406Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0406Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0406Client(cc grpc.ClientConnInterface) Zhaoh0406Client {
	return &zhaoh0406Client{cc}
}

func (c *zhaoh0406Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0406.sample_package_0406.Zhaoh0406/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0406Server is the server API for Zhaoh0406 service.
// All implementations must embed UnimplementedZhaoh0406Server
// for forward compatibility
type Zhaoh0406Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0406Server()
}

// UnimplementedZhaoh0406Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0406Server struct {
}

func (UnimplementedZhaoh0406Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0406Server) mustEmbedUnimplementedZhaoh0406Server() {}

// UnsafeZhaoh0406Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0406Server will
// result in compilation errors.
type UnsafeZhaoh0406Server interface {
	mustEmbedUnimplementedZhaoh0406Server()
}

func RegisterZhaoh0406Server(s grpc.ServiceRegistrar, srv Zhaoh0406Server) {
	s.RegisterService(&Zhaoh0406_ServiceDesc, srv)
}

func _Zhaoh0406_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0406Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0406.sample_package_0406.Zhaoh0406/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0406Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0406_ServiceDesc is the grpc.ServiceDesc for Zhaoh0406 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0406_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0406.sample_package_0406.Zhaoh0406",
	HandlerType: (*Zhaoh0406Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0406_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0406.proto",
}
